"""create initial tables

Revision ID: 011711b50665
Revises: 
Create Date: 2026-06-29 14:26:37.122180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '011711b50665'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('itens_venda', 'venda_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('itens_venda', 'produto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('itens_venda', 'preco_unitario',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('itens_venda', 'subtotal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.add_column('usuarios', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('usuarios', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('vendas', sa.Column('status', sa.String(length=20), nullable=False))
    op.alter_column('vendas', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('vendas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_vendas_status'), 'vendas', ['status'], unique=False)
    op.create_index(op.f('ix_vendas_usuario_id'), 'vendas', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendas_usuario_id'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_status'), table_name='vendas')
    op.alter_column('vendas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendas', 'total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('vendas', 'status')
    op.drop_column('usuarios', 'updated_at')
    op.drop_column('usuarios', 'created_at')
    op.alter_column('itens_venda', 'subtotal',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('itens_venda', 'preco_unitario',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('itens_venda', 'produto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('itens_venda', 'venda_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
