"""initial_com_saidas_uuid

Revision ID: 25ffdcc33e42
Revises: 
Create Date: 2026-07-22 09:13:28.951015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ffdcc33e42'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saidas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loja_id', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saidas_id'), 'saidas', ['id'], unique=False)
    op.create_index(op.f('ix_saidas_loja_id'), 'saidas', ['loja_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saidas_loja_id'), table_name='saidas')
    op.drop_index(op.f('ix_saidas_id'), table_name='saidas')
    op.drop_table('saidas')
    # ### end Alembic commands ###
