"""add observacao e created_at venda

Revision ID: 274448712f3e
Revises: 06cf22663d14
Create Date: 2026-08-19 09:36:00.165947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274448712f3e'
down_revision: Union[str, Sequence[str], None] = '06cf22663d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('observacao', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendas', 'observacao')
    # ### end Alembic commands ###
