"""add categoria e fornecedor

Revision ID: 299a7ec5213d
Revises: 523d3597a06c
Create Date: 2026-07-04 18:33:29.566284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299a7ec5213d'
down_revision: Union[str, Sequence[str], None] = '523d3597a06c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categorias_slug'), table_name='categorias')
    op.drop_column('categorias', 'is_active')
    op.drop_column('categorias', 'descricao')
    op.drop_column('categorias', 'slug')
    op.drop_column('fornecedores', 'is_active')
    op.drop_column('fornecedores', 'observacao')
    op.drop_column('fornecedores', 'endereco')
    op.drop_column('fornecedores', 'cnpj')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fornecedores', sa.Column('cnpj', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('fornecedores', sa.Column('endereco', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('fornecedores', sa.Column('observacao', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('fornecedores', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('categorias', sa.Column('slug', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('categorias', sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('categorias', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_categorias_slug'), 'categorias', ['slug'], unique=True)
    # ### end Alembic commands ###
