"""init

Revision ID: 3adcd1cf9aca
Revises: 
Create Date: 2026-07-16 16:29:04.978309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3adcd1cf9aca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lojas',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('nif', sa.String(length=14), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('ano_fundacao', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('card_style', sa.String(length=20), nullable=False),
    sa.Column('card_size', sa.String(length=20), nullable=False),
    sa.Column('font_size', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lojas_slug'), 'lojas', ['slug'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('categorias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loja_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_loja_id'), 'categorias', ['loja_id'], unique=False)
    op.create_table('documentos_kyc',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loja_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('bi', 'alvara', 'certificado', name='tipo_documento_enum', native_enum=False), nullable=False),
    sa.Column('url_arquivo', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'aprovado', 'reprovado', name='status_kyc_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loja_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fornecedores_loja_id'), 'fornecedores', ['loja_id'], unique=False)
    op.create_table('usuarios_lojas',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('loja_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DONO', 'GERENTE', 'VENDEDOR', 'CAIXA', 'ESTOQUISTA', 'MULTI_LOJA', name='userrole'), nullable=False),
    sa.Column('cargo', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'loja_id', 'id')
    )
    op.create_table('vendas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loja_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_itens', sa.Integer(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=False),
    sa.Column('valor_recebido', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('troco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loja_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('codigo_barras', sa.String(length=50), nullable=True),
    sa.Column('codigo_qr', sa.Text(), nullable=True),
    sa.Column('ncm', sa.String(length=10), nullable=True),
    sa.Column('preco_compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_promocao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('margem_lucro', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('custo_medio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.Column('estoque_maximo', sa.Integer(), nullable=True),
    sa.Column('unidade', sa.Enum('UN', 'KG', 'CX', 'GRADE', 'CESTA', 'PCT', 'LT', 'MT', name='unidadeenum'), nullable=False),
    sa.Column('peso_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('fornecedor_id', sa.UUID(), nullable=True),
    sa.Column('localizacao', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_categoria_id'), 'produtos', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_produtos_codigo_barras'), 'produtos', ['codigo_barras'], unique=False)
    op.create_index(op.f('ix_produtos_loja_id'), 'produtos', ['loja_id'], unique=False)
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=False)
    op.create_index(op.f('ix_produtos_sku'), 'produtos', ['sku'], unique=False)
    op.create_table('itens_venda',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venda_id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('loja_id', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_venda')
    op.drop_index(op.f('ix_produtos_sku'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_loja_id'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_codigo_barras'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_categoria_id'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_table('vendas')
    op.drop_table('usuarios_lojas')
    op.drop_index(op.f('ix_fornecedores_loja_id'), table_name='fornecedores')
    op.drop_table('fornecedores')
    op.drop_table('documentos_kyc')
    op.drop_index(op.f('ix_categorias_loja_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_lojas_slug'), table_name='lojas')
    op.drop_table('lojas')
    # ### end Alembic commands ###
