"""add nif and telefone to lojas

Revision ID: 3b9a723532c6
Revises: 1cbe8f0bec18
Create Date: 2026-07-06 23:31:02.151412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b9a723532c6'
down_revision: Union[str, Sequence[str], None] = '1cbe8f0bec18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
