"""add cor_primaria and cor_fundo to lojas

Revision ID: 4cfa6a7ea610
Revises: ea3bd84c3706
Create Date: 2026-07-16 20:40:05.153223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cfa6a7ea610'
down_revision: Union[str, Sequence[str], None] = 'ea3bd84c3706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lojas', sa.Column('cor_primaria', sa.String(length=7), server_default='#10b981', nullable=False))
    op.add_column('lojas', sa.Column('cor_fundo', sa.String(length=7), server_default='#000', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lojas', 'cor_fundo')
    op.drop_column('lojas', 'cor_primaria')
    # ### end Alembic commands ###
