"""add ultima_compra to cliente

Revision ID: 4f61470edc5e
Revises: 006846b0cb39
Create Date: 2026-08-11 12:15:32.788582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f61470edc5e'
down_revision: Union[str, Sequence[str], None] = '006846b0cb39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Adiciona colunas novas como nullable
    op.add_column('clientes', sa.Column('total_divida', sa.Float(), nullable=True))
    op.add_column('clientes', sa.Column('ultima_compra', sa.DateTime(timezone=True), nullable=True))

    # 2. Preenche dados nulos dos clientes antigos
    op.execute("UPDATE clientes SET total_divida = 0.0 WHERE total_divida IS NULL")
    op.execute("UPDATE clientes SET updated_at = created_at WHERE updated_at IS NULL") # <- FIX AQUI

    # 3. Agora sim trava como NOT NULL
    op.alter_column('clientes', 'total_divida', nullable=False)
    op.alter_column('clientes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    op.alter_column('movimentos_vendas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendas', 'total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('vendas', 'valor_recebido',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('vendas', 'troco',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendas', 'troco',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('vendas', 'valor_recebido',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('vendas', 'total',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('movimentos_vendas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('clientes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('clientes', 'ultima_compra')
    op.drop_column('clientes', 'total_divida')
    # ### end Alembic commands ###
