"""add is_active to lojas

Revision ID: 5d6c53e08513
Revises: 011711b50665
Create Date: 2026-06-30 21:25:23.691132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6c53e08513'
down_revision: Union[str, Sequence[str], None] = '011711b50665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # CORREÇÃO 1: loja_id em 3 passos pra não travar
    op.add_column('itens_venda', sa.Column('loja_id', sa.UUID(), nullable=True)) # 1. Cria aceitando NULL
    op.execute("UPDATE itens_venda SET loja_id = (SELECT id FROM lojas LIMIT 1) WHERE loja_id IS NULL") # 2. Preenche com 1 loja
    op.alter_column('itens_venda', 'loja_id', nullable=False) # 3. Trava como NOT NULL
    op.create_index(op.f('ix_itens_venda_loja_id'), 'itens_venda', ['loja_id'], unique=False)
    op.create_foreign_key(None, 'itens_venda', 'lojas', ['loja_id'], ['id'])
    
    # CORREÇÃO 2: is_active em 3 passos
    op.add_column('lojas', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE lojas SET is_active = true WHERE is_active IS NULL")
    op.alter_column('lojas', 'is_active', nullable=False, server_default='true')

    op.drop_index('ix_produtos_sku', table_name='produtos')
    op.drop_column('produtos', 'sku')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index('ix_produtos_sku', 'produtos', ['sku'], unique=True)
    op.drop_column('lojas', 'is_active')
    op.drop_constraint(None, 'itens_venda', type_='foreignkey')
    op.drop_index(op.f('ix_itens_venda_loja_id'), table_name='itens_venda')
    op.drop_column('itens_venda', 'loja_id')
    # ### end Alembic commands ###