"""add forma_pagamento to movimentacao_caixa

Revision ID: 7399e324d395
Revises: e4280631a39a
Create Date: 2026-08-04 16:28:28.601552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7399e324d395'
down_revision: Union[str, Sequence[str], None] = 'e4280631a39a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimentacoes_caixa', sa.Column('forma_pagamento', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movimentacoes_caixa', 'forma_pagamento')
    # ### end Alembic commands ###
