"""initial_schema

Revision ID: 81e2b918abe9
Revises: 
Create Date: 2026-07-22 08:53:07.621619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81e2b918abe9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saidas', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('saidas', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('saidas', 'valor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('saidas', 'descricao',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(op.f('saidas_criado_por_fkey'), 'saidas', type_='foreignkey')
    op.drop_constraint(op.f('saidas_loja_id_fkey'), 'saidas', type_='foreignkey')
    op.create_foreign_key(None, 'saidas', 'lojas', ['loja_id'], ['id'])
    op.drop_column('saidas', 'criado_em')
    op.drop_column('saidas', 'criado_por')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saidas', sa.Column('criado_por', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('saidas', sa.Column('criado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'saidas', type_='foreignkey')
    op.create_foreign_key(op.f('saidas_loja_id_fkey'), 'saidas', 'lojas', ['loja_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('saidas_criado_por_fkey'), 'saidas', 'usuarios', ['criado_por'], ['id'])
    op.alter_column('saidas', 'descricao',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('saidas', 'valor',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('saidas', 'updated_at')
    op.drop_column('saidas', 'created_at')
    # ### end Alembic commands ###
