"""create clientes table and add cliente_id to vendas

Revision ID: b0eeb88166e0
Revises: ccc8116508e2
Create Date: 2026-08-06 10:57:35.047168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0eeb88166e0'
down_revision: Union[str, Sequence[str], None] = 'ccc8116508e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loja_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('nome_empresa', sa.String(length=255), nullable=True),
    sa.Column('bi', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_bi'), 'clientes', ['bi'], unique=False)
    op.create_index(op.f('ix_clientes_loja_id'), 'clientes', ['loja_id'], unique=False)
    op.create_index(op.f('ix_clientes_telefone'), 'clientes', ['telefone'], unique=False)
    op.add_column('vendas', sa.Column('cliente_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_vendas_cliente_id'), 'vendas', ['cliente_id'], unique=False)
    op.create_foreign_key(None, 'vendas', 'clientes', ['cliente_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendas', type_='foreignkey')
    op.drop_index(op.f('ix_vendas_cliente_id'), table_name='vendas')
    op.drop_column('vendas', 'cliente_id')
    op.drop_index(op.f('ix_clientes_telefone'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_loja_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_bi'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
