"""add nif to cliente

Revision ID: c659ac0fe650
Revises: 4ed14a23e128
Create Date: 2026-08-24 10:56:05.944610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c659ac0fe650'
down_revision: Union[str, Sequence[str], None] = '4ed14a23e128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('nif', sa.String(length=14), nullable=True))
    op.create_index(op.f('ix_clientes_nif'), 'clientes', ['nif'], unique=False)
    op.drop_column('usuarios_lojas', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios_lojas', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_clientes_nif'), table_name='clientes')
    op.drop_column('clientes', 'nif')
    # ### end Alembic commands ###
