"""add gerente relations

Revision ID: ddb5a2050693
Revises: 5d6c53e08513
Create Date: 2026-07-01 16:28:54.331186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb5a2050693'
down_revision: Union[str, Sequence[str], None] = '5d6c53e08513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_loja')
    op.add_column('lojas', sa.Column('gerente_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'lojas', 'usuarios', ['gerente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lojas', type_='foreignkey')
    op.drop_column('lojas', 'gerente_id')
    op.create_table('usuario_loja',
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('loja_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], name=op.f('usuario_loja_loja_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('usuario_loja_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('usuario_id', 'loja_id', name=op.f('usuario_loja_pkey'))
    )
    # ### end Alembic commands ###
