"""add indice unico caixa aberto por usuario

Revision ID: f518a275c156
Revises: 00280536fe92
Create Date: 2026-07-23 11:07:44.496414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f518a275c156'
down_revision: Union[str, Sequence[str], None] = '00280536fe92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_mov_caixa_caixa_id'), table_name='movimentacao_caixa')
    op.drop_index(op.f('idx_mov_caixa_loja_data'), table_name='movimentacao_caixa')
    op.drop_table('movimentacao_caixa')
    op.alter_column('caixa', 'usuario_abertura_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('caixa', 'status',
               existing_type=postgresql.ENUM('aberto', 'fechado', name='statuscaixa'),
               type_=sa.Enum('aberto', 'fechado', name='statuscaixa', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_caixa_data_caixa'), 'caixa', ['data_caixa'], unique=False)
    op.create_index(op.f('ix_caixa_loja_id'), 'caixa', ['loja_id'], unique=False)
    op.create_index(op.f('ix_caixa_status'), 'caixa', ['status'], unique=False)
    op.create_index(op.f('ix_caixa_usuario_abertura_id'), 'caixa', ['usuario_abertura_id'], unique=False)
    op.create_index('ix_caixa_usuario_dia_aberto', 'caixa', ['loja_id', 'usuario_abertura_id', 'data_caixa'], unique=True, postgresql_where=sa.text("status = 'aberto'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_caixa_usuario_dia_aberto', table_name='caixa', postgresql_where=sa.text("status = 'aberto'"))
    op.drop_index(op.f('ix_caixa_usuario_abertura_id'), table_name='caixa')
    op.drop_index(op.f('ix_caixa_status'), table_name='caixa')
    op.drop_index(op.f('ix_caixa_loja_id'), table_name='caixa')
    op.drop_index(op.f('ix_caixa_data_caixa'), table_name='caixa')
    op.alter_column('caixa', 'status',
               existing_type=sa.Enum('aberto', 'fechado', name='statuscaixa', native_enum=False),
               type_=postgresql.ENUM('aberto', 'fechado', name='statuscaixa'),
               existing_nullable=False)
    op.alter_column('caixa', 'usuario_abertura_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('movimentacao_caixa',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('caixa_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('loja_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('valor', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('referencia_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('referencia_tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("tipo::text = ANY (ARRAY['entrada'::character varying, 'saida'::character varying, 'sangria'::character varying, 'abertura'::character varying]::text[])", name=op.f('ck_mov_tipo')),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], name=op.f('movimentacao_caixa_loja_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('movimentacao_caixa_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('movimentacao_caixa_pkey'))
    )
    op.create_index(op.f('idx_mov_caixa_loja_data'), 'movimentacao_caixa', ['loja_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_mov_caixa_caixa_id'), 'movimentacao_caixa', ['caixa_id'], unique=False)
    # ### end Alembic commands ###
